spring.application.name=ml-service
spring.datasource.url=jdbc:mysql://localhost:3306/goods_service_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=9999

# C?u hình cho Google Cloud
google.cloud.project-id=warehouse-439807
dialogflow.project-id=warehouse-439807
dialogflow.credentials.file-path=dialogflow-service-account.json


openai.api.url=https://api.openai.com/v1/completions
//openai.api.key = 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
openai.api.key = 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
GOOGLE_APPLICATION_CREDENTIALS=recommendations.json
