server:
  port: 8888

app:
  api-prefix: /v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product_service
          uri: http://localhost:8084
          predicates:
          - Path=${app.api-prefix}/api/brands/**, ${app.api-prefix}/api/images/**, ${app.api-prefix}/api/prices/**, ${app.api-prefix}/api/products/**, ${app.api-prefix}/api/product-groups/**
          filters:
          - StripPrefix=1
        - id: goods_service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/api/deliveryNotes/**, ${app.api-prefix}/api/receipts/**, ${app.api-prefix}/api/receipt-details/**, ${app.api-prefix}/api/suppliers/**
          filters:
            - StripPrefix=1
        - id: employee_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/api/attendances/**, ${app.api-prefix}/api/employees/**, ${app.api-prefix}/api/payrolls/**, ${app.api-prefix}/api/wage-configurations/**, ${app.api-prefix}/api/workshifts/**
          filters:
            - StripPrefix=1
        - id: order_service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/api/invoices/**,${app.api-prefix}/api/return-notes/**, ${app.api-prefix}/api/return-details/**, ${app.api-prefix}/api/customers/**, ${app.api-prefix}/api/invoice-details/**
          filters:
            - StripPrefix=1
        - id: inventory_service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/api/batches/**, ${app.api-prefix}/api/batch-details/**, ${app.api-prefix}/api/inventory-check-slips/**, ${app.api-prefix}/api/locations/**
          filters:
            - StripPrefix=1
        - id: identity_service
          uri: http://localhost:8089
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=1
