server:
  port: 8888

app:
  api-prefix: /v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product_service
          uri: http://localhost:8084
          predicates:
          - Path=${app.api-prefix}/api/products/**
          filters:
          - StripPrefix=1
        - id: goods_service
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/api/receipts/**
          filters:
            - StripPrefix=1
        - id: employee_service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/api/employees/**
          filters:
            - StripPrefix=1
        - id: order_service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/api/invoices/**
          filters:
            - StripPrefix=1
