spring.application.name=employee-service

spring.datasource.url=jdbc:mysql://root:NmBgTczJOHhbdMHCRpGTEzziFTmyseJu@crossover.proxy.rlwy.net:57722/railway

spring.datasource.username=root
spring.datasource.password=NmBgTczJOHhbdMHCRpGTEzziFTmyseJu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085
